### ISSUE TITLE
Visualização de filmes em exibição

### ISSUE THREAD

**Issue by Kibo1999** [Imeguras/AInet_2022#5]
Todos os utilizadores da aplicação, **incluindo utilizadores anónimos** (qualquer utilizador é anónimo
antes de fazer o login) deverão conseguir **consultar os filmes em exibição** no cinema "CineMagic". Considera-se que um filme está em exibição, se tiver **pelo menos uma sessão para o dia de hoje ou qualquer dia posterior**. Para cada filme a aplicação deverá apresentar o **título**, o **cartaz**, o **sumário**, um **trailer** (se existir), bem como as **sessões do filme** (só as sessões do dia de hoje ou dias posteriores), em que para cada sessão deverá ser apresentada a **sala**, **data**, **hora de início** e algo que
indique se a sessão **está esgotada ou não**.

**Comment by Imeguras** [comment]
Meio feito, falta o cartaz, as sessoes do filme a sala, data e hora, tambem falta por ultimo se a sessao ta esgotada
de qualquer maneira este commit apresenta-se ser viavel para dar merge ao master

**Comment by Imeguras** [comment]
ya isto foi merged ***Alguem*** esqueceu-se de fazer as etapas todas
